#-----------------------------------------------------------------------------
#
#  Configuration for continuous integration service at travis-ci.org
#
#-----------------------------------------------------------------------------

language: cpp

sudo: false
dist: trusty

matrix:
    include:
        - os: linux
          compiler: clang
          env: USE_PYTHON_VERSION=2
        - os: linux
          compiler: clang
          env: USE_PYTHON_VERSION=3
        - os: linux
          compiler: gcc
          env: USE_PYTHON_VERSION=2
        - os: linux
          compiler: gcc
          env: USE_PYTHON_VERSION=3
        - os: osx
          osx_image: xcode6.4
          compiler: clang
          env: USE_PYTHON_VERSION=2 PYTHON_SUFFIX=2 BOOST_PYTHON_OPTION=
        - os: osx
          osx_image: xcode6.4
          compiler: clang
          env: USE_PYTHON_VERSION=3 PYTHON_SUFFIX=3 BOOST_PYTHON_OPTION="--with-python3 --without-python"
        - os: osx
          osx_image: xcode7
          compiler: clang
          env: USE_PYTHON_VERSION=2 PYTHON_SUFFIX= BOOST_PYTHON_OPTION=
        - os: osx
          osx_image: xcode7
          compiler: clang
          env: USE_PYTHON_VERSION=3 PYTHON_SUFFIX=3 BOOST_PYTHON_OPTION="--with-python3 --without-python"

# http://docs.travis-ci.com/user/apt/
addons:
    apt:
        sources:
            - boost-latest
        packages:
            - g++-4.8
            - gcc-4.8
            - libboost-python1.55-dev
            - libboost1.55-dev
            - libsparsehash-dev
            - python-dev
            - python-nose
            - python-mock
            - python3
            - python3-dev
            - python3-nose
            - python3-setuptools

install:
    - git clone --quiet --depth 1 https://github.com/osmcode/libosmium.git ../libosmium
    - git clone --quiet --depth 1 https://github.com/mapbox/protozero.git ../protozero
    - if [ "$TRAVIS_OS_NAME" = 'osx' ]; then
          brew update;
          brew install python$PYTHON_SUFFIX google-sparsehash;
          brew install boost-python $BOOST_PYTHON_OPTION;
          pip$PYTHON_SUFFIX install -q nose mock;
      fi

script:
    - if [ "${CXX}" = 'g++' ]; then
          CXX=g++-4.8;
          CC=gcc-4.8;
      fi
    - if [ "$TRAVIS_OS_NAME" = 'osx' ]; then
          PYTHON=python${USE_PYTHON_VERSION};
      else
          PYTHON=/usr/bin/python${USE_PYTHON_VERSION};
      fi
    - $PYTHON --version
    - $PYTHON setup.py build
    - $PYTHON setup.py bdist_wheel
    - cd test
    - $PYTHON run_tests.py

deploy:
  provider: s3
  skip_cleanup: true
  acl: public_read
  region: eu-west-1
  local_dir: dist
  access_key_id: ${AWS_ACCESS_KEY_ID}
  secret_access_key: ${AWS_SECRET}
  bucket: pyosmium
